#!/bin/bash

HOSTS=( "$@" )

HOSTS[0]="${HOSTS[0]:-pi2-testing}" #if no server specified, default to pi2-testing
PASSWD="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/passwd" #grabs passwd file from same directory as this script

if [ ! -e "$PASSWD" ]; then
	echo "Unable to read password file $PASSWD"
	exit
fi

for SERVER in "${HOSTS[@]}"; do
	(ping -c 1 ${SERVER} > /dev/null 2> /dev/null && echo "Casting to $SERVER") || echo "$SERVER is offline"
done

for SERVER in "${HOSTS[@]}"; do
	(hostname > /dev/tcp/$SERVER/12345) > /dev/null 2> /dev/null
done

echo "Press ctrl+c to exit"
x11vnc -display $DISPLAY -rfbauth "$PASSWD" -viewonly -ncache 16 -q -bg > /dev/null 2> /dev/null

