#!/bin/bash

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

showHelp () {
	cat help.txt
	exit
}

runServer () {
	echo -e "Waiting for someone to cast to this screen...\nOn the computer you want to cast, run the command: cast $(hostname)"
	$DIR/server
	exit
}

if [ "$1" == "--help" ] || [ "$1" == "-help" ]; then showHelp; fi

while getopts sr:h option; do
	case "${option}" in
		s) runServer;;
		r) RES=${OPTARG};;
		h) showHelp;;
	esac
done
shift $(($OPTIND - 1))

if [ -z "$RES" ]; then RES="1440x900"; fi

xrandr -s "$RES"

$DIR/client ${@}

xrandr -s 1920x1200 #Reset back to original resolution
