#!/bin/bash

DEFAULT="pi2-200c"
HOSTS=( "$@" )
HOSTS[0]="${HOSTS[0]:-$DEFAULT}"
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
PASSWD="$DIR/../pass/passwd"
PORT="12345"

if [ ! -e "$PASSWD" ]; then echo "Unable to read password file $PASSWD"; exit; fi

#Are they online?
for HOST in $HOSTS; do
	(ping -c 1 $HOST > /dev/null 2> /dev/null && echo "Casting to $HOST from $(hostname)") || echo "$HOST is offline"
done

for HOST in $HOSTS; do
	((hostname > "/dev/tcp/$HOST/$PORT") > /dev/null 2> /dev/null) || echo "Error casting to $HOST"
done

echo "Want better framerates? Use cast -r [width]x[height] to lower the resolution and speed up casting. To view available resolutions, run xrandr."
echo "Press ctrl+c to exit"
x11vnc -display $DISPLAY -rfbauth "$PASSWD" -viewonly -q -bg > /dev/null 2> /dev/null
