#!/bin/bash

PASSWD="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../pass/passwd" #grabs passwd file from same directory as this script
PORT="12345"

if [ ! -e "$PASSWD" ]; then echo "Unable to read password file $PASSWD"; exit; fi

echo "$(date) - Server started and listening on port $PORT" >> castServer.log

while true; do
	HOST=$(nc -l -p $PORT)
	if [ -n "$HOST" ]; then
		sleep 2
		echo "$(date) - $HOST" >> castServer.log
		vncviewer $HOST -passwd $PASSWD -encodings raw -fullscreen
	fi
done 

