#!/bin/bash
#Author: Pierce Stegman

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

showHelp () {
	cat $DIR/help.txt
	exit
}

runServer () {
	echo -e "Waiting for someone to cast to this screen...\nOn the computer you want to cast, run the command: cast $(hostname)"
	$DIR/server
	exit
}

if [ "$1" == "--help" ] || [ "$1" == "-help" ]; then showHelp; fi

while getopts sr:h option; do
	case "${option}" in
		s) runServer;;
		r) RES=${OPTARG};;
		h) showHelp;;
	esac
done
shift $(($OPTIND - 1))

if [ -z "$RES" ]; then RES="1440x900"; fi

OLDRES=$(xrandr --current 2>/dev/null | grep "\*" | awk 'NR==1{print $1}')
xrandr -s "$RES"

$DIR/client ${@}

xrandr -s $OLDRES #Reset back to original resolution
